CXX = g++
CXXFLAGS = -g  -std=c++11 -Wall#-I(include) -L(lib dir) -l(libname)
OBJ = parser.o lexer.o 

main: $(OBJ) main.o 
	$(CXX) $(CXXFLAGS) $(OBJ) main.cc -o $@ 

#TODO type check
test: lexer_test parser_test symbol_table_test 

lexer_test: lexer.o
	$(CXX) -o $@ lexer_test.cc lexer.o $(CXXFLAGS) 
parser_test: $(OBJ)
	$(CXX) -o $@  parser_test.cc $(OBJ) $(CXXFLAGS) 
symbol_table_test: $(OBJ)
	$(CXX) -o $@  symbol_table_test.cc $(OBJ) $(CXXFLAGS) 


lexer.o: lexer.h
parser.o: lexer.h node.h symbol_table.h

.PHONY: clean
clean:
	-rm -f main test
	-rm -f *.o 
